### ISSUE TITLE
Plot n levels of tree

### ISSUE THREAD

**Issue by mattiasthalen** [parrt/dtreeviz#137]
Not sure where to put feature requests, so I'm trying it here.
Please correct me if I'm wrong :)

I have a tree that consists of 10 levels. Plotting this tree is a nightmare when it comes to readability.
So what I thought was that it would be great if we could set a max_depth for the tree plotting, so it only builds up to the specified levels.

What do you think?
Or would it be better to just train a seperate tree with the purpose of just visualizing?

**Comment by tlapusan** [comment]
hi @mattiasthalen, by creating an issue like this one, it is the right place for a new feature :)

if you want to reduce the max_depth, you can do this when you train the model.

indeed, it is not very easy to see what it's happening in a big tree if you plot its structure. That's why we created other visualisations likes  viz_leaf_samples, viz_leaf_criterion, deschibe_node_samples.
you can take a look at all visualisation mothod in this notebook https://github.com/parrt/dtreeviz/blob/master/notebooks/dtreeviz_sklearn_visualisations.ipynb

**Comment by tlapusan** [comment]
hi @mattiasthalen, is my above comment a possible solution for you ? if yes, I would like to close this issue :)

**Comment by mattiasthalen** [comment]
Yes!

I opted on just plotting the "prediction path" instead of showing the entire tree.
