### ISSUE TITLE
ShadowXGBDTree: 'Booster' object has no attribute 'save_config'

### ISSUE THREAD

**Issue by thatgeeman** [parrt/dtreeviz#148]
The issue can be reproduced [here (collab)](https://colab.research.google.com/drive/1NX9ob3o1lpe2CHrEhd3O7vP15syQ9trK?usp=sharing). In the notebook, I call the modified class `ShadowXGBDTree__` for demonstration.
In this class, `_isXGB` is introduced as a boolean flag in `hasattr(booster, 'get_booster')` to correctly set the `booster` and `config` items. Non-breaking changes were made to `is_classifier` and `get_max_depth` methods to correctly read the booster params. I can submit a PR with the modifications.

**Comment by parrt** [comment]
Thanks, @thatgeeman !

**Comment by tlapusan** [comment]
Hi @thatgeeman, I will have time to look on it in the early next week, hope it is not too late

**Comment by thatgeeman** [comment]
No problem! thank you for looking into it @parrt @tlapusan

**Comment by tlapusan** [comment]
hi @thatgeeman, nice that you created that notebook and I had your environment to check the issue.

The issue is that you are using an old xgboost version (0.9.0) and the save_config() method was added only from version 1.0 https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.Booster.save_config

Do you have the possibility to increase the xgboost version (I'm using 1.4.2) and to check again ? 

The support for XGBClassifier and XGBRegressor was added few months ago by @oegedijk, here https://github.com/parrt/dtreeviz/pull/115/commits/63f97168b542a16436e85bbdc0e51bb4cc685ddd

**Comment by thatgeeman** [comment]
@tlapusan Yes, you are correct! Upgraded to 1.4.2 and the methods work as expected :100: 
Thank you for taking the time to go through it! :) I will close this issue now.
