### ISSUE TITLE
Comparisons between trees ensembles?

### ISSUE THREAD

**Issue by thvasilo** [parrt/dtreeviz#165]
Hello,

I'm interested in visualizing differences between trees, so I was wondering if I could use some of the the primitives provided by dtreeviz to provide easily digestible "diffs" between trees. The idea is that I've trained an HPO job, and I want to decide which of the 5-10 best-performing models to use, based on some characteristics they might share or have difference.
For example, I might prefer the models where a particular feature has more importance, or I might prefer shallower trees etc.

This is definitely an open-ended question/feature request, but which of the visualizations currently provided you think would adapt well to visualizing as "differences" between different tree ensemble models?

**Comment by tlapusan** [comment]
Hi @thvasilo,

from the provided visualisations, the best I can think of for your use case are the tree leaves visualisations : https://github.com/parrt/dtreeviz#leaf-node-purity
Since the tree performance is given by its leaves, you could inspect them and make an idea if they are different...

Hope that it will help. 
In the end, if you have ideas of how to better find differences between trees, we would appreciate if you can share them ;)

**Comment by thvasilo** [comment]
Thanks, I'll take a look at those and see what else I can come up with :)
